#!/bin/sh

pypath="${NCS_DIR}/src/ncs/pyapi"

# Make sure everyone finds the NCS Python libraries at startup
if [ "x$PYTHONPATH" != "x" ]; then
    PYTHONPATH=${pypath}:$PYTHONPATH
else
    PYTHONPATH=${pypath}
fi
export PYTHONPATH

main="${pypath}/ncs_pyvm/startup.py"

# input argument 6 is the package name
echo "Starting ${main} $*"

#activating the virtual environment for the package
for path in ${PYTHONPATH//:/ }; do
    basename=$(basename $path)
    package=$(basename $(dirname $path))
    packagepath=$(dirname $path)
    #locate the python package path in $PYTHONPATH and check if it has a virtualenv
    if [ "$basename" == "python" ] && [ "$package" == "$6" ] && [ -f "$packagepath/env/bin/activate" ]; then
        echo "Found virtualenv for package $6, activating it"
        source $packagepath/env/bin/activate
    fi
done

# bin/python3packages.txt should be in a bin folder in the NSO runtime folder
if [ ! -z $(grep $6 "bin/python3packages.txt") ]; then
    echo "Starting python v3 vm for package $6"
    exec python3 -u ${main} $*
else
    echo "Starting the system default python vm for package $6"
    exec python -u ${main} $*
fi




